[package]
name = "withered"
version = "0.1.0"
authors = ["AnonymousDapper <jreasley14@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"

[profile.release]
panic = "abort"
